name: housingsociety
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.0
  flutter_spinkit: ^5.0.0
  provider: ^6.1.5
#  modal_bottom_sheet: ^2.0.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  percent_indicator: ^4.2.5
  flutter_tts: ^4.2.3
  translator: ^1.0.3+1
#  rake:
  pie_chart: ^5.0.0
#  connectivity: 3.0.6
#  firebase_core: 1.14.1
#  firebase_auth: 3.3.14
#  cloud_firestore: 3.1.12
#  cloud_firestore: ^3.5.1
#  firebase_storage: 10.2.12
  # Firebase (latest versions as of mid-2024)
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7

  # Modal bottom sheet (if needed)
  modal_bottom_sheet: ^3.0.0
  flutter: 
    sdk: flutter
  intl: ^0.20.2
  connectivity_plus: ^6.1.4

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/default_profile_pic.jpg
  uses-material-design: true

